[package]
name = "rs2s"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "1.1.0"
http_input = { version = "0.1.0", path = "../../http_input" }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
